- id: 0
  dns_name: "party0"
  bind_addr: "127.0.0.1:10000"
  public_addr: "127.0.0.1:10000"
  cert_path: "data/cert0.der"
- id: 1
  dns_name: "party1"
  bind_addr: "127.0.0.1:11000"
  public_addr: "127.0.0.1:11000"
  cert_path: "data/cert1.der"
- id: 2
  dns_name: "party2"
  bind_addr: "127.0.0.1:12000"
  public_addr: "127.0.0.1:12000"
  cert_path: "data/cert2.der"
